# require classes to test
require './book'
require './classroom'
require './person'
require './rental'
require './student'
require './teacher'
require './decorator'
require './trimmer_decorator'
require './capitalize_decorator'
